### ISSUE TITLE
[Bug]: The @api.video/react-player package disappeared from NPM

### ISSUE THREAD

**Issue by DmitriyNikolenko** [apivideo/api.video-react-player#11]
### Version

1.0.1

### Environment that reproduces the issue

NodeJS

### Is it reproducible in the example application?

Yes

### Reproduction steps

Run `yarn add @api.video/react-player`

### Expected result

The package installed

### Actual result

`[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@api.video%2freact-player: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/dmitriynikolenko/Projects/Connect-web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

### Additional context

Happens today

**Comment by DmitriyNikolenko** [comment]
![Screenshot 2023-02-15 at 17 23 41](https://user-images.githubusercontent.com/25880968/219071313-c5c423be-f410-46ea-9cdb-ffbbdcb1e458.png)

**Comment by MarDi66** [comment]
Hey @DmitriyNikolenko 👋🏼 
We just fixed the issue, it should be working fine now :) 
Sorry for the inconvenience!
