### ISSUE TITLE
[Bug]: Video playback not working in Mac Safari

### ISSUE THREAD

**Issue by will-grange-inclusive** [apivideo/api.video-react-player#20]
### Version

@api.video/react-player@1.0.4

### Environment that reproduces the issue

Reproducible at least on:
Mac Safari 16.6.1 (16615.3.12.11.5, 16615)
Mac Safari 17.5 (17618.2.12.111.5, 17618)

### Is it reproducible in the example application?

Yes

### Reproduction steps

Instantiate an instance of ApiVideoPlayer in React and launch in Mac Safari 16.6.1/17.5.

```
     <ApiVideoPlayer
        autoplay={true}
        video={{ id: videoId }}
        chromeless={true}
        style={playerStyles}
      />
```

The "thumb" image will appear, but when playback starts the video is black. The video audio output can still be heard.

Please note that this can also be reproduced in the dashboard of [api.video](https://dashboard.api.video/) so may be a broader issues than just the react player.

### Expected result

The video is visible during playback.

### Actual result

The video is blank/black during playback.

**Comment by will-grange-inclusive** [comment]
I have attached a screen recording of video playback experience in Safari 16.6.1 in the api.video dashboard:
https://github.com/apivideo/api.video-react-player/assets/134401053/4702d0f8-9579-4a95-a252-bbb3aaa04fc7

**Comment by olivierapivideo** [comment]
Hi @will-grange-inclusive ,
Thanks for reporting this and sorry for the inconvenience, we are working on a fix.

**Comment by olivierapivideo** [comment]
Hi @will-grange-inclusive 
The issue has been fixed. Your private videos should now appear properly in the dashboard. 
Please note that you'll have to use the `customDomain` attribute of the React player to have private videos working properly with your custom domain.

Don't hesitate to reopen if you still have issues.
