### ISSUE TITLE
[Bug]: Frequently get 404s from https://{our-custom-embed-domain}/assets/plugins/core-player/player.{some-hash}.js 

### ISSUE THREAD

**Issue by will-grange-inclusive** [apivideo/api.video-react-player#24]
### Version

@api.video/react-player@1.0.4

### Environment that reproduces the issue

Any device/browser

### Is it reproducible in the example application?

Yes

### Reproduction steps

This is intermettent but does occur quite frequently, espectially if the player has not been requested touched for a few hours.
- Request a video using the react player

### Expected result

Video always players

### Actual result

- Video does not load/appears black
- A 404 can be seen in the browser console: net::ERR_ABORTED 404 (Not Found) for https://{our-custom-embed-domain}/assets/plugins/core-player/player.{some-hash}.js 

Note: I can see the player alternating between these builds each time it happens:

{our-custom-embed-domain}/assets/plugins/core-player/player.41853fe.js
{our-custom-embed-domain}/assets/plugins/core-player/player.e93e1d3.js

Could this be that the player is load balanced but serving different builds?

**Comment by olivierapivideo** [comment]
Hi @will-grange-inclusive,

Thank you for reporting this, and sorry for the inconvenience.

We've deployed a fix. Can you try again?

If you're still facing the issue, can you provide us with a sample page where we would be able to reproduce the bug, or at least a snippet of your code where you're using the `<ApiVideoPlayer>` tag?

By the way we're also taking in charge the other issues you've reported.

**Comment by olivierapivideo** [comment]
Hi @will-grange-inclusive,

Thank you for your patience and for providing additional details. 

The issue you experienced was due to an exceptional problem during the last deployment of the player. One load-balanced node did not had the latest version of the bundle, which caused inconsistencies in certain cases. That was probably the cause of the issue you mentioned in this issue.

**Comment by will-grange-inclusive** [comment]
OK, thanks for the detail of the cause, that make sense. As we have not since encoutered the 404 response testing, and our monitoring hasn't picked this up either we are happy to close this issue. Thanks for resolving.
