### ISSUE TITLE
[Bug]: JS error on production player on a live

### ISSUE THREAD

**Issue by ChoOo7** [apivideo/api.video-react-player#28]
### Version

Latest, your live player on production

### Environment that reproduces the issue

Chrome on windows

### Is it reproducible in the example application?

Not tested

### Reproduction steps

                                    i.videoJsPlayer.paused() || 0 < i.lastForcedReloadTime && (new Date).getTime() - i.lastForc < edReloadTime < 2e4 || (t = i.videoJsPlayer.currentTime(),

Uncaught ReferenceError: edReloadTime is not defined
    at player.787c8d9.js:2:1181351

on https://embed.api.video/assets/plugins/core-player/player.787c8d9.js
![image](https://github.com/user-attachments/assets/e5b5e7be-75ad-439c-992d-21e69b1f9bd8)

### Expected result

no red on my console :)

### Actual result

red on my console

**Comment by olivier-lando** [comment]
Hi @ChoOo7 ,
We've just fixed this issue. Sorry for that.
Regards,
Olivier

**Comment by ChoOo7** [comment]
Thanks, have a good day
